### ISSUE TITLE
MySQL are supported?

### ISSUE THREAD

**Issue by gflp123** [pietermartin/sqlg#149]
sqlg currently Postgresql, HSQLDB, and H2 database are supported.
Any suggestions，If I want use MySql,Thanks

**Comment by pietermartin** [comment]
To make Sqlg work on MYSQL we need to implement `org.umlg.sqlg.sql.dialect.SqlDialect`

There is a partial implementation for MariaDB. I stopped implementing it as I do not use MariaDB personally and there was no interest in it at the time.

The primary challenge regarding MariaDB/MYSQL is that it does not support schemas. Instead a separate database needs to be created for each schema. Seeing as MariaDB/MYSQL supports cross database queries it is pretty much the same as having schemas.

**Comment by gflp123** [comment]
The primary challenge regarding MariaDB/MYSQL is that it does not support schemas?
Can explain in detail.

Whether there is value to achieve MySql Supported.

**Comment by pietermartin** [comment]
Postgresql, H2, HSQLDB and I think SqlServer and Oracle all support the notion of a schema as a namespacing mechanism.
MYSQL does not, but it can be simulated by having a db per schema.

Sqlg supports schemas.
```
        Vertex car = graph.addVertex(T.label, "Fleet.Car");
        graph.addVertex(T.label, "Fleet.Bike");
        Vertex human = graph.addVertex(T.label, "Mammal.Human");
        graph.addVertex(T.label, "Mammal.Dog");
        human.addEdge("drives", car);
        graph.tx().commit();
        List<Vertex> cars =  graph.traversal().V().hasLabel("Mammal.Human").out("drives").toList();
        assertEquals(1, cars.size());

```
In Postgres/H2/HSQLDB this will create 2 schemas, Fleet and Mammal
In the Fleet schema there will be 2 tables, Car and Bike
In the Mammal schema there will be 2 tables Human and Dog

To achieve the same in MYSQL Fleet and Mammal will have the a database each.
Since joining across databases in MYSQL is not a problem the rest of Sqlg should work fine.

Regarding the value of supporting MYSQL.  I am pretty sure it will be valuable. However I am not now in a position to commit time to implementing this.

If you or anyone wants to implement the dialect I'll be happy to review the PRs.
