### ISSUE TITLE
Deadlock between table locks and topology locks

### ISSUE THREAD

**Issue by JPMoresmau** [pietermartin/sqlg#217]
See https://github.com/pietermartin/sqlg/compare/master...JPMoresmau:bugfix/deadlock?expand=1#diff-52d150b2b9dda2c31c8a9420da1ad88e

The test looks contrived but this is as far as I can tell what happens inside our software, which is of course really annoying. We have a thread that performs a traversal on an edge table, and another that adds an edge to a new vertex label running concurrently. The reading thread has locked the table while reading it, and then requires the topology read lock (during traversal or on commit). The writing thread required to add a new column and foreign key to the edge table, so has acquired the topology lock, and tries to get a lock on the table. Deadlock.

Not sure what's the best way to fix this. Should all threads take a read lock on the topology when they open a transaction? That will cause modifications of the topology to have to wait for all other transactions...
In our code we share the same sqlggraph (in distributed mode since we also have several processes) between threads, as tests show that creating different instances is both slow and quickly starve the database connections...

**Comment by JPMoresmau** [comment]
Tested with two different graphs, there are no deadlocks, because of course they don't share a topology lock. Even if the configuration says "distributed=true". So it looks like the same operations deadlock when done on the same graph and don't when done on different graphs.

**Comment by JPMoresmau** [comment]
One first thing that can be done is to use LOCK_TIMEOUT also for the read lock. In this case there is no deadlock, the reading thread just aborts in error. This is probably better than a deadlock...

**Comment by JPMoresmau** [comment]
My bugfix/deadlock branch now uses lock timeout for the read lock, and this is configurable. So at least now we fail the reading thread instead of deadlocking. Let me know if we can do more to remove the failure altogether.

**Comment by pietermartin** [comment]
I am looking at this today, rather critical that we get this right.

**Comment by pietermartin** [comment]
Just to check, You say you share the same graph in distributed mode. Don't really understand that, distributed mode is only for multiple graphs. Either in the same jvm or different but different graph instances. Do you have distributed=true even though there is only one graph?

Further I noticed `beforeCommit` produces the notification json even if distributed is false. That part is unnecessary, including the taking of a read lock for no reason, but does not resolve the potential for dead lock. Your test however then no longer deadlocks.

The readLock only protects reading the actual topology maps. So its generally held very briefly. But still as you have shown its possible to dead lock when postgres is unable to take a table lock but holding a topology lock.

**Comment by pietermartin** [comment]
Ok, I pushed the topology partial fix. Can you test on your system to see if it still dead locks? Your tests passes without the need for timeouts. I'll look more as dead locks are still possible but harder to reproduce now.

**Comment by JPMoresmau** [comment]
OK, will test tomorrow. Just to be clear: we run sqlg with distributed=true because we have multiple nodes and JVMs, but we also have multithreaded programs and the deadlock occured inside one of these programs.

**Comment by pietermartin** [comment]
Hi, my change will have no effect on your setup. It only improves the situation for when distribution=false.
So no need to test yet.

**Comment by pietermartin** [comment]
Ok, I have fixed it in the `optionalWithOrder` branch.
Basically its a new locking strategy as the previous one was simply not going to work.

Here is how I see the problem,
1) Thread1 open transaction (idle in transaction connection in postgres)
2) Thread2 open transaction, change the topology, i.e. take a topology write lock and execute a sql `alter` statement. (sql statement blocks waiting for thread1's connection to complete)
3) Thread1 tries to get a read lock, (read locks are taken all over the show when reading the topology maps) 
4) Voila dead lock as Thread2 is holding the write lock.

Reckon the reason we have not seen it happen much is because the read locks are only held briefly.

The way I see it, the topology write lock can not be taken while there are other transactions open as the sql statement will block anyhow. So while previously the read lock was held only while actually reading the map it will now be help for any and every transaction and be upgraded to a write lock if it actually tried to change the topology.

How it works now,
Every transaction immediately takes a read lock on the topology.

If a topology change needs to take place it upgrades the read lock to a write lock. The write lock will block till there are no more read locks.

All locks are released on commit or rollback.

All tests are passing, including some new dead lock tests. I have not tested it yet on the work systems. Will do so tomorrow.

**Comment by JPMoresmau** [comment]
I'm a bit afraid that any change to the topology will have to wait for all other transactions to complete. Given the inherent dynamic nature of the schema, isn't that a problem?

**Comment by pietermartin** [comment]
Yeah, I too am afraid of that.

Occasionally that is the case anyways as a schema change takes a table lock which will block till all other transactions on the affected elements are gone. It fine grained though where Sqlg now locks db wide.

The idea is that schema changes in general happens very seldom and that if transactions are kept short the system's throughput should be ok. At least now it won't dead lock.

I am still trying to think of a better way but so far nothing has come to mind. Perhaps by understanding the queries meta data better the locking can be finer grained. It will make the code rather complex though.

I am testing the next few days with this to see if I notice any slow down.

**Comment by pietermartin** [comment]
Ok, so I am trying another strategy. The previous, though not dead locking is to strict.
Got 2 separate locks now. 
One regular ReentractLock to make sure only one thread/connection can make sql schema changes at a time.
And one ReadWriteReentrant lock to protect the various topology caches.
So the first no longer blocks on purely reading connections.

All tests are passing but will test this at work next week.

**Comment by pietermartin** [comment]
All is looking good with our testing.
@JPMoresmau can you test the `optionalWithOrder` branch and if all is well I'll merge it into master and do a release soon after.
Its deployed in maven central as 1.4.0-SNAPSHOT
