### ISSUE TITLE
Concurrent queries to a graph with sized connections pool leads to deadlock.

### ISSUE THREAD

**Issue by dipstef** [pietermartin/sqlg#269]
Hi,
First of all thanks for this project, we find it really useful!

We have recently put in place in my company a gremlin-server/Sqlg based solution for dispatching queries over Postgresql.
Initially our load testing results were promising and not highlighting any performance issue, but after a recent increase in traffic on the server we started to experience performance degradation and even having some  instances of this service being completely locked out. 

After some initial investigation and more testing, we have realised that in the simple scenario where db connections are limited by a connection pool, and with a number of threads that exceeds this upper limit of connections, we get a deadlock condition  where one the working threads is waiting indefinitely for a connection slot.

The following code snippet highlights this problem:
https://gist.github.com/dipstef/fef66b7b5d2fc2a2dea5bc0e1cca073f

Would you kindly look into this issue?

Do you have any suggestion for things that we can try on the gremlin server side to mitigate this issue? We were thinking about trying to change the size of the workersPool to match the size of the db connection pool.

Thanks for looking into this!

**Comment by pietermartin** [comment]
Hi, yes I'll have a look. Need to understand why its deadlocking.
Say are you using gremlin server because you are connecting via a language other than java?

**Comment by pietermartin** [comment]
The reason for the deadlock is because a transaction is opened in `queryTask` but it does not `commit` or `rollback` the transaction.
Transaction are thread scoped so the connection is thread scoped and is only returned to the pool on `commit` or `rollback`

Changing `queryTask` to
```
    private static Callable<Integer> queryTask(Graph graph, int recordId) {
        return () -> {
            Integer result = recordValue(graph, recordId);
            graph.tx().rollback();
            return result;
        };
    }
```
makes the test pass.

It is very easy to leak transaction in Sqlg and gremlin for that matter. Everything should be wrapped in a try finally rollback.

At my day job to make things safer we use a custom wrapped `ExecutorService` which always calls `graph.tx().rollback()` when the thread is returned to the pool. It is possible to override the `ThreadPoolExecutor`'s `afterExecute` method and rollback in there.
For the web server we have a filter that calls `graph.tx().rollback()`.

**Comment by pietermartin** [comment]
Did you come right?

**Comment by pietermartin** [comment]
Closing this, open it again if the solution is not as described.
