### ISSUE TITLE
Incorrect translation of `outE().hasLabel(...)`

### ISSUE THREAD

**Issue by metlos** [pietermartin/sqlg#51]
It looks like `...outE("label")` is translated correctly while the semantically equivalent `...outE().hasLabel("label")` is not.

The generated SQL tries to look for a column called `~label` in some table (seems not to even be the correct edge table). That column does not exist and the query fails.

I might be able to look into this but since I'm quite new to your codebase I'd appreciate some guidance.

**Comment by metlos** [comment]
This is the test I've added to `TestTraversals.java` to demonstrate this:

```java
    @Test
    public void g_V_outE_hasLabel_inV() {
        loadModern();
        List<Vertex> vertices = gt.V().outE().hasLabel("created").inV().toList();
        Assert.assertEquals(2, vertices.size());
    }
```

**Comment by pietermartin** [comment]
Thanks, sure looks like a bug. 
I doubt I have any tests covering that scenario and it seems Tinkerpop neither. I'd start by looking at `SqlgGraphStepStrategy.combineSteps` and in there `collectHasSteps`. Although it looks like the `HasStep` is combined but that the value\parameter is incorrectly set. I'll investigate this evening.

**Comment by metlos** [comment]
I tried to do something yesterday - having missed the `collectHasSteps` method I tried to implement my own strategy to basically look for any `has(T.label, ...)` steps and merge them into a preceding `VertexStep` but then I realized it would not work because that approach would fail to handle constructs like:
```java
...outE().not(__.hasLabel("myLabel")).inV()
```

So currently I'm a little bit at loss how to implement this...

**Comment by pietermartin** [comment]
Hi,

The main entry point for this bug is `GremlinParser.parse(List<ReplacedStep<S, E>> replacedSteps)`

`SchemaTableTree` represents a tree for which a sql query can be constructed. 

`SchemaTableTree.removeAllButDeepestLeafNodes()` removes nodes that are to shallow. i.e. `g.V.out.out.out` invalidates the parts of the graph where it is only possible to do 1 or 2 hops (traversals). This also captures the leaf nodes of the tree to be used later.

`SchemaTableTree.removeNodesInvalidatedByHas` removes nodes that are invalidated by `HasContainer`s.

And this is where the bug came in. I created the leaf for invalid nodes.

First removing all invalid nodes and then creating the leaf nodes fixed the bug.
