### ISSUE TITLE
Validate sqlg topology on startup

### ISSUE THREAD

**Issue by pietermartin** [pietermartin/sqlg#70]
With Sqlg storing the topology itself there is the risk that the schema will be changed via straight sql.
In this case Sqlg will be unaware of the change and its topology will be incorrect.

We need a way to validate the topology and auto fix it. Mostly this is a concern when schema elements are dropped in which case Sqlg will generate invalid sql and crash gloriously.

**Comment by JPMoresmau** [comment]
On the topic of graph schema and topology, I see the methods in Schema Manager that would allow to create the schema on demand like ensureVertexTableExists are package protected, not public (while the edge tables methods are public). Is there a reason for it? I would think of use cases where we would like to define the schema first and then populate data. Thanks

**Comment by pietermartin** [comment]
I am busy refactoring the `SchemaManager` to reflect the topology as stored in `sqlg_schema`.
`SchemaManager` is/was the first incarnation, before storing the topology natively in `sqlg_schema`.

So those methods will all disappear soon to reappear in else where. They were however not intended for clients to use.

Regarding upfront schema creation my idea was to have some json/xml format to specify it in, including being able to export the current schema. 

However for many it might be easier to use the java api. I'll keep it in mind with the current refactor.

Thanks

**Comment by metlos** [comment]
I have the exact same problem as @JPMoresmau that I solved by just making those methods public in my fork ;) Because I know about your current effort with `SchemaManager` refactoring I didn't really bother with creating a PR, though I was going to create an issue for this, which I no longer have to :)

Having the ability to create the schema upfront is quite necessary in our case, because the database has to survive occasional write bursts, which at the same time are likely to trigger the initial schema "creation". Having the database schema altered several times while trying to serve many many write and read requests proves to be problematic. Fortunately in our case, much of the schema is known upfront, so we can "be prepared". Just for the record, the code (referencing the forked Sqlg codebase) is here: https://github.com/metlos/hawkular-inventory/blob/c35ea2ea882b92cee745fbe1216995e0dff88328/hawkular-inventory-impl-tinkerpop-parent/hawkular-inventory-impl-tinkerpop-sql-provider/src/main/java/org/hawkular/inventory/impl/tinkerpop/sql/SqlGraphProvider.java#L142

**Comment by pietermartin** [comment]
The way I have solved this problem is by creating the fake vertices and edges simulating the schema in initialization code, committing and then deleting them again. Bit of a hack but it ensures the schema is created.
I am somewhat hesitant to just make those methods public as I have no tests cases for this.
I'll be sure to consider this usage for the refactor.

**Comment by JPMoresmau** [comment]
Thanks for the answers. If you're looking for a way to express the schema, I wonder if supporting GraphQL would not give us the best of both world. Using a java implementation of GraphQL we could translate the GraphQL schema definition into calls to your schema creation methods, and get GraphQL support alongside TinkerPop for nearly free! Sorry, I'm dreaming...

**Comment by pietermartin** [comment]
Yeah, I'd have to investigate GraphQL to understand their semantics. Some dreams might come true.

**Comment by pietermartin** [comment]
The idea is to only validate that Sqlg's topology exists.
This way tables can be added outside of Sqlg and they will be ignored. Unless `sqlg_schema` is dropped in which case they too will get loaded.
