### ISSUE TITLE
Select statement contains duplicate columns

### ISSUE THREAD

**Issue by JPMoresmau** [pietermartin/sqlg#78]
A simple query like `g.traversal().V().has("id", 0).valueMap()` generates SQL that lists twice all the columns. This has a performance impact (returning data twice, etc.). 
The cause is that in SchemaTableTree.constructFromClause we build a list of columns for both the lastSchemaTableTree and all the tables referenced by firstSchemaTableTree. But I arrive here with both SchemaTableTree being the same, and columns get duplicated. So far all attempts to remove the duplication cause things to fail later in tests we seem to be expecting these aliases...

**Comment by pietermartin** [comment]
Yeah, I am aware of this. Its non trivial to fix but definitely must be done. Its a confusion between always returning leaf nodes in the call tree and needing to return all nodes in path queries.
The aliasing is necessary as Postgresql only allows 63 characters for a column name.

**Comment by pietermartin** [comment]
BTW its also not possible in Sqlg to select only a few columns. At present the whole row is returned.

**Comment by JPMoresmau** [comment]
OK, I have some code that fixes the issue + refactor the sql generation code to make it cleaner in that spot. I'll run some more tests before submitting a PR

**Comment by pietermartin** [comment]
I see `LocalDateTest` is failing because on `ZonedDateTime` types. `ZonedDateTime` maps to multiple columns. DateTime and ZoneId. It is only failing on Postgresql and passing on Hsqldb. Need to investigate whats happening there.

**Comment by JPMoresmau** [comment]
Yep, I had "fixed" I thought a bug, where when we generate code for the "labeled" columns, we didn't call the "labeled" alias method for postfixes. This change is what is causing the test to fail, if I revert to the old behavior the test passes. I don't understand the main purpose of this code, so  just revert, check the tests and will submit another PR.

**Comment by pietermartin** [comment]
Not sure which part you are getting and which not but here goes a description.

The `postFixes` indicates if a property type maps to more than one column.
`java.time` `ZonedDateTime`, `Duration` and `Period` currently map to more than one column.
The first column will be labeled as per normal, the extra columns do not need a label.

Sqlg strategy, for good or bad, was to encode the meta information in the sql column name.
So eg,

```
        Vertex a1 = this.sqlgGraph.addVertex(T.label, "A", "name", "a1");
        Vertex b1 = this.sqlgGraph.addVertex(T.label, "B", "name", "b1");
        a1.addEdge("ab", b1);
        this.sqlgGraph.tx().commit();

        List<Map<String, Vertex>> result = this.sqlgGraph.traversal()
                .V()
                .hasLabel("A").as("a", "aa", "aaa")
                .out("ab").as("b", "bb", "bbb")
                .<Vertex>select("a", "aa", "aaa", "b", "bb", "bbb")
                .toList();

        for (Map<String, Vertex> stringVertexMap : result) {
            for (Map.Entry<String, Vertex> stringVertexEntry : stringVertexMap.entrySet()) {
                String label = stringVertexEntry.getKey();
                Vertex vertex = stringVertexEntry.getValue();
                System.out.println("label = " + label + ", vertex name =  " + vertex.value("name"));
            }
        }
```
Will output,
```
label = a, vertex name =  a1
label = aa, vertex name =  a1
label = aaa, vertex name =  a1
label = b, vertex name =  b1
label = bb, vertex name =  b1
label = bbb, vertex name =  b1
```
And execute sql
```
SELECT
	"public"."V_B"."ID" AS "alias1",
	"public"."V_B"."name" AS "alias2",
	"public"."V_A"."ID" AS "alias3",
	"public"."V_A"."name" AS "alias4"
FROM
	"public"."V_A" INNER JOIN
	"public"."E_ab" ON "public"."V_A"."ID" = "public"."E_ab"."public.A__O" INNER JOIN
	"public"."V_B" ON "public"."E_ab"."public.B__I" = "public"."V_B"."ID"
```

At first Sqlg encoded the meta data into to column name itself.
So unaliased the column names will be
```
        alias1 = 2P~~~b~&~2P~~~bb~&~2P~~~bbb~&~public~&~V_B~&~ID
        alias2 = 2P~~~b~&~2P~~~bb~&~2P~~~bbb~&~public~&~V_B~&~name
        alias3 = 1P~~~aa~&~1P~~~aaa~&~1P~~~a~&~public~&~V_A~&~ID
        alias4 = 1P~~~aa~&~1P~~~aaa~&~1P~~~a~&~public~&~V_A~&~name
```
The numeric indicates the depth/degree of the out/in, or after the strategy has  run the depth of the SchemaTableTree.
'P' stands for TinkerPop's notion of Path. For `RepeatStep` together with `emit` an 'E' used instead of a 'P'.
'~~~' and '~&~' are just separators.
So one can tell that alias1 is second degree in the `SchemaTableTree` and has 3 labels and is for the "ID" field/property.

All this information is needed to reconstruct the sql `ResultSet` back into a gremlin stream.

For queries that contain the `PathStep` but does not have specified labels, i.e. `as("a")` Sqlg will generate fake labels. From there the same code can execute to reconstruct the gremlin Paths.

As the column names became too long for Postgresql 63 character limit I aliased them and stored the column name with the meta data in a ThreadVar.

This can be further refactored to use a proper data structure rather than a long special string which is a hangover from when it was an actual column name.

Thanks again for the PR.
